const SUPABASE_URL =
  "COLE_SUA_URL_SUPABASE_AQUI";

const SUPABASE_KEY =
  "COLE_SUA_CHAVE_SUPABASE_AQUI";

const SUPABASE_FAT_URL =
  "COLE_SUA_TABELA_FATURAMENTO_AQUI";

const SUPABASE_LINKS_URL =
  "COLE_SUA_TABELA_LINKS_AQUI";